import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/Header-Footer/Footer";
import Header from "@/Components/Header-Footer/Header";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Header />
				<Toaster />
				<main className="flex min-h-[90vh] flex-col items-center gap-4 p-4 bg-white">
					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
}
